services:
  - type: web
    name: vibelog-pro-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: YOUR_MONGO_URI_HERE
      - key: JWT_SECRET
        value: YOUR_JWT_SECRET_HERE
      - key: CLIENT_URL
        value: YOUR_CLIENT_URL_HERE
      - key: CLOUDINARY_CLOUD_NAME
        value: YOUR_CLOUDINARY_CLOUD_NAME_HERE
      - key: CLOUDINARY_API_KEY
        value: YOUR_CLOUDINARY_API_KEY_HERE
      - key: CLOUDINARY_API_SECRET
        value: YOUR_CLOUDINARY_API_SECRET_HERE
